config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  get 'welcome/index'

  get 'transactions', to: 'transactions#index'
  post 'transactions', to: 'transactions#create'

  get 'kontua', to: 'user#kontua'
  post 'kontua', to: 'user#kontua'
  post 'kontuBerria', to: 'user#create'

  get 'login', to: 'user_session#index'
  post 'login', to: 'user_session#create'
  post 'user_session', to: 'user_session#create'
  delete 'logout', to: 'user_session#destroy'

  get 'signup', to: 'new_user#index'
  get 'signup', to: 'new_user#create'
end

app/models/account.rb
class Account < ApplicationRecord
	validates :kontu_zenbakia, presence: true
    validates :erabiltzaile_id, presence: true
    validates :sortze_data, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
   validates :bidaltzaile_kontua, presence: true
   validates :hartzaile_kontua, presence: true
   validates :kopurua, presence: true

   

end

app/models/user.rb
class User < ApplicationRecord
    has_many :accounts

    def self.authenticate(nan, password)  
    	@user = User.where(:nan => nan).first
    	if @user
			if @user.pasahitza == password
		    	return @user
		 	else
			    return false
			end
		else
			return false
		end
    end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/new_user_controller.rb
class NewUserController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    nan = session[:user_nan]
    @kontuak = Account.where(:erabiltzaile_id => nan)
    @transaction = Transaction.new
  end

  # POST /transactions
  def create
    kontu_zenbakia = params[:transaction][:bidaltzaile_kontua]
    hartzaile_kontua = params[:transaction][:hartzaile_kontua]
    kopurua = params[:transaction][:kopurua].to_f
    azalpena = params[:transaction][:azalpena]

    @accountBidali = Account.find(kontu_zenbakia)

    if @accountBidali.kopurua>=kopurua && kopurua>0
      if Account.exists?(kontu_zenbakia: hartzaile_kontua)
        @accountJaso = Account.find(hartzaile_kontua)
        ActiveRecord::Base.transaction do

          if Transaction.last
            @transaction = Transaction.new do |t|
              t.id = Transaction.last.id + 1,
              t.bidaltzaile_kontua = kontu_zenbakia,
              t.azalpena = azalpena,
              t.hartzaile_kontua = hartzaile_kontua,
              t.kopurua = kopurua,
              t.data = Time.now.strftime("%Y-%m-%d")
            end
          else
            @transaction = Transaction.new do |t|
              t.id = 0,
              t.bidaltzaile_kontua = kontu_zenbakia,
              t.azalpena = azalpena,
              t.hartzaile_kontua = hartzaile_kontua,
              t.kopurua = kopurua,
              t.data = Time.now.strftime("%Y-%m-%d")
            end
          end
          totalBidaltzaile = @accountBidali.kopurua-kopurua
          totalJasotzaile = @accountJaso.kopurua+kopurua

          @accountBidali = @accountBidali.update_attribute(:kopurua, totalBidaltzaile)
          @accountJaso = @accountJaso.update_attribute(:kopurua, totalJasotzaile)

          @transaction.save
        end
        flash[:notice] = "bidalketa gauzatu egin da"
        redirect_to(:transactions, message: "Dirua bidali nahi den kontu zenbakia ez da existitzen")
      else
        flash[:alert] = "Dirua bidali nahi den kontu zenbakia ez da existitzen"
        redirect_to(:transactions, message: "Dirua bidali nahi den kontu zenbakia ez da existitzen")
      end
    else
      flash[:alert] = "Dirua kopurua ez da egokia"
      redirect_to(:transactions, message: "Dirua kopurua ez da egokia")
    end 
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def create
    nan = session[:user_nan]

    if Account.last
      @account = Account.new do |a|
          a.kontu_zenbakia = Account.last.kontu_zenbakia.to_i + 1
          a.erabiltzaile_id = nan
          a.kopurua = "0"
          a.sortze_data = Time.now.strftime("%Y-%m-%d")
        end
      @account.save()
    else
      @account = Account.new do |a|
          a.kontu_zenbakia = "1234567890000"
          a.erabiltzaile_id = nan
          a.kopurua = "0"
          a.sortze_data = Time.now.strftime("%Y-%m-%d")
        end
      @account.save()
    end

    redirect_to(:kontua, message: "Kontu berria sortu da")
  end

  def kontua
  	nan = session[:user_nan]
  	@erabiltzailea = User.find(nan)
  	@kontuak = Account.where(:erabiltzaile_id => nan)
    @transakzioak = []
    @kontuak.each do |kontua|
  	  transAux = Transaction.where(:bidaltzaile_kontua => kontua.kontu_zenbakia)
      if transAux.empty?
      else
        @transakzioak += transAux
      end
    end
  end
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
	def index

 	end

  	# GET /user_session/new
	def new
		@user = User.new
	end 

	# POST /user_session
	def create
		nan = params[:user][:nan]
		pass = params[:user][:password]
		@user = User.authenticate(nan, pass)
		if @user
		    flash[:notice] = "Wow Welcome again"
		    session[:user_nan] = @user.nan
		    session[:user_izena] = @user.izena
		    redirect_to(:controller => 'user', :action => 'kontua')
		else
		    flash[:alert] = "Invalid Username or Password"
	    	render "index"	
		end
	end

	# DELETE /user_session/:id
	def destroy
		session.clear
		redirect_to(:root, message: "Logged out")
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_user_helper.rb
module NewUserHelper
end

app/helpers/operazioa_helper.rb
module OperazioaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SGTAOsagarria</title>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">
        <%= link_to "Sarebank", root_path, :class=>"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <% if session[:user_izena] %>
              	<li class="nav-item">
              	  <%= link_to "Log Out", logout_path, method: :delete, :class=>"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to session[:user_izena], "/kontua", :class=>"nav-link", method: :post%>
              	</li>
              <% else %>
      	      	<li class="nav-item">
              	  <%= link_to "Sign Up", "/signup", :class=>"nav-link" %>
               	</li>
                <li class="nav-item">
                  <%= link_to "Log In", "/login", :class=>"nav-link" %>
                </li>  
              <% end %>    
            </ul>
          </div>
      </div>
    </nav>

    <div class="content">
      <%= yield %>
    </div>

    <footer class="py-3 bg-black">
      <div class="container">
        <a href="http://github.com/augarte/SGTA_Osagarria" target="_blank">
          <center>  
            <%= image_tag("GitHub.png", :alt=>"GitHub", :class=>"github img-fluid rounded-circle")%>
          </center>
        </a> 
      </div>
    </footer>
  </body>
</html>

app/views/new_user/index.html.erb
<header class="headerMenu masthead text-center text-white" style="padding: 1rem; position:fixed; left: 0px; top:4rem; width: 100%; height: 6rem;">
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div> 
    <div class="bg-circle-4 bg-circle"></div>
    <h1 class="h3 mb-3 font-weight-bold" style="position:relative;z-index: 10;margin-top: 1.5rem; color: black">
        Please sign up
    </h1>
</header>

<section style="margin-top: 15%">

    <%= form_for(   :user,
                    :url => {:controller => 'new_user', :action => 'create'},
                    :html => {:class=>"form-signin", :style=>"z-index: -1"}) do |f|%>

        <div class="text-center" >            
            <%= f.label :nanLabel, :class=>"sr-only" %>
            <%= f.text_field :nan, :id=> "inputNan", :class=>"form-control", placeholder:"NAN", :required => true%>
            <%= f.label :passwordLabel, :class=>"sr-only"%>
            <%= f.password_field :password, :id=> "inputPassword", :class=>"form-control", placeholder: "Pasahitza", :required => true%>
            <%= f.label :emailaLabel, :class=>"sr-only"%>
            <%= f.text_field :emaila, :id=> "inputEmail", :class=>"form-control", placeholder: "Emaila", :required => true%>
            <%= f.label :izenaLabel, :class=>"sr-only"%>
            <%= f.text_field :izena, :id=> "inputIzena", :class=>"form-control", placeholder: "Izena", :required => true%>
            <%= f.label :abizenakLabel, :class=>"sr-only"%>
            <%= f.text_field :abizenak, :id=> "inputAbizenak", :class=>"form-control", placeholder: "Abizenak", :required => true%>
            <%= f.label :telefonoaLabel, :class=>"sr-only"%>
            <%= f.text_field :telefonoa, :id=> "inputTelefonoa", :class=>"form-control", placeholder: "Telefonoa", :required => true%>
            <%= f.label :helbideaLabel, :class=>"sr-only"%>
            <%= f.text_field :helbidea, :id=> "inputHelbidea", :class=>"form-control", placeholder: "Helbidea", :required => true%>
            </div>

            <div class="actions">
                <%= f.submit :"Sign Up", :class=>"btn btn-lg btn-primary btn-block submitButton", disabled: true %>
                <label>Funtzio hau ez dago prest</label>
            </div>
            <p class="mt-5 mb-3 text-muted"></p>
        </div>
    <% end %>

</section>

app/views/transactions/index.html.erb
<header class="headerMenu masthead text-center text-white" style="padding: 1rem; position:fixed; left: 0px; top:4rem; width: 100%">
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>

  <h2>Ongi etorri, <%= session[:user_id] %></h2>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container" >
      <ul class="navbar-nav ml-auto" style="width: 100%; text-align: center;">
        <li>
          <%= link_to "Kontuaren infromazioa", "kontua", :method => :post, :class=>"nav-link" %>
        </li>
        <li>
          <%= link_to "Transakzioen historia", "kontua", :method => :post, :class=>"nav-link" %>
        </li>
        <li>
          <label id="tBerria_l" class="nav-link bold" style="cursor: pointer;">
            Transakzio berria
          </label>
        </li>
      </ul>
    </div>
  </nav>

</header>

<section class="col-sm-12" style="margin-top: 13rem; padding: 2.5rem;">
	<h1>Transakzio berria</h1>
	<p>Egin transakzio berri bat:</p>
	<%= form_for( :transaction,
                :method => "post",
                :url => {:controller => 'transactions', :action => 'create'}
                ) do |f| %>

      <%= f.select 'bidaltzaile_kontua', options_from_collection_for_select(@kontuak, 'kontu_zenbakia', 'kontu_zenbakia'), :required => true%>

  		<%= f.label :hartzaile_kontuaL,'Hartzailearen kontua: ', :class=>"sr-only" %>
    	<%= f.text_field :hartzaile_kontua, :class=>"form-control", placeholder: "Hartzailearen kontu zenbakia", style:"width:250px;", :required => true%>

  		<%= f.label :azalpenaL,'Transazioaren azalpena: ', :class=>"sr-only" %>
    	<%= f.text_field :azalpena, :class=>"form-control", placeholder: "Azalpena", style:"width:250px;"%>

  		<%= f.label :kopuruaL,'Diru kopurua: ', :class=>"sr-only" %>
    	<%= f.text_field :kopurua, :class=>"form-control", placeholder: "Kopurua (€)", style:"width:150px;", :required => true%>

  	<div class="actions" style="margin-top: 2rem">
        <%= f.submit :"Bidali", :class=>"btn btn-lg btn-primary bold btn-block submitButton", style:"width:100px; color: black"%>
    </div>
    <center>
      <label class="notice"><%= notice %></label>
      <label class="alert" style="color: red"><%= alert %></label>
    </center>

  	<% @transaction.errors.full_messages.each do |message| %>
      <div style="color: red;">
      	* <%= message %>
      </div>
    <%end%>
<% end %> 
</section>

app/views/transactions/new.html.erb
<h1>Transakzio berria</h1>
<p>Egin transakzio berri bat:</p>
<%= form_for (@transaction) do |f| %>
  <div class="field">
     Hartzailearen kontua: <%= f.text_field :hartzaile_kontua, placeholder: "Hartzailearen kontu zenbakia", style:"width:250px;" %>
  </div>
  <div class="field">
     Transazioaren azalpena: <br/>
     <%= f.text_field :azalpena, placeholder: "Azalpena", style:"width:400px;" %>
  </div>
  <div class="field">
     Diru kopurua: <%= f.text_field :kopurua %>€
  </div>
  <div class="field">
     <%= f.submit "Bidali" %>
  </div>
  <% @transaction.errors.full_messages.each do |message| %>
      <div style="color: red;">
      	* <%= message %>
      </div>
  <%end%>
<% end %> 

app/views/transactions/show.html.erb
<h3><%= @transaction.azalpena %></h3>
<div>
    <p><%= @transaction.data %></p>
    <p>Hartzaile kontua: <%= @transaction.hartzaile_kontua %></p> <p>Zenbatekoa: <%= @transaction.kopurua %>€</p>
</div>

app/views/user/kontua.html.erb
<header class="headerMenu masthead text-center text-white" style="padding: 1rem; position:fixed; left: 0px; top:4rem; width: 100%">
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>

  <h2>Ongi etorri, <%= session[:user_id] %></h2>
  <nav class="navbar navbar-expand-lg navbar-light">
		<div class="container" >
			<ul class="navbar-nav ml-auto" style="width: 100%; text-align: center;">
				<li>
					<label id="info_l" class="nav-link bold" style="cursor: pointer;">
						Kontuaren informazioa
					</label>
				</li>
				<li>
					<label id="tHistoria_l" class="nav-link bold" style="cursor: pointer;">
						Transakzioen historia
					</label>
				</li>
				<li>
					<%= link_to "Transakzio berria", "/transactions", :class=>"nav-link bold" %>
				</li>
			</ul>
		</div>
	</nav>

</header>

<section class="col-sm-12" style="margin-top: 13rem; padding: 2.5rem;">
	<div id="info_d" class="col-sm-12 sekzioDiv">
		<table class="infoTaula">
			<tr>
				<td><label class="bold">Nan: </label></td>
				<td><label class="tab"><%=@erabiltzailea.nan%></label></td>
			</tr>
			<tr>
				<td><label class="bold">Izena: </label></td>
				<td><label class="tab"><%=@erabiltzailea.izena%></label></td>
			</tr>
			<tr>
				<td><label class="bold">Abizena: </label></td>
				<td><label class="tab"><%=@erabiltzailea.abizenak%></label></td>
			</tr>
			<tr>
				<td><label class="bold">Emaila: </label></td>
				<td><label class="tab"><%=@erabiltzailea.emaila%></label></td>
			</tr>
			<tr>
				<td><label class="bold">Helbidea: </label></td>
				<td><label class="tab"><%=@erabiltzailea.helbidea%></label></td>
			</tr>
			<tr>
				<td><label class="bold">Telefonoa: </label></td>
				<td><label class="tab"><%=@erabiltzailea.telefonoa%></label></td>
			</tr>
		</table>
		<table class="col-sm-12 kontuakTaula">
			<tr>
				<td>
					<label class="bold">Kontuak:</label> 
				</td>
				<td>
					<label class="bold">Kopurua:</label> 
				</td>
				<td rowspan="<%=@kontuak.count+1%>">
					<%= link_to "kontuBerria", :method => :post do%>
						<%= image_tag("add.png", :alt=>"add", :style=>"height: 25px")%>
					<%end%>
				</td>
			</tr>
			<%@kontuak.each do |kontua|%>
			<tr>
				<td>
					<label><%=kontua.kontu_zenbakia %></label>
				</td>
				<td>
					<label><%=kontua.kopurua %>€</label>
				</td>
			</tr>
			<%end%>
		</table>
	</div>

	<div id="tBerria_d" class="sekzioDiv"> 
	</div>

	<div id="tHistoria_d" class="sekzioDiv">
		<table class="col-sm-12 transakzioTaula" style="z-index: -1; display: block;">
			<%@transakzioak.each do |transakzioa|%>
				<tbody class="tTbody">
					<tr>
						<td>
							<label class="bold">Zure kontua:</label> 
						</td>
						<td>
							<label><%=transakzioa.bidaltzaile_kontua%></label>
						</td>
					</tr>
					<tr>
						<td>
							<label class="bold">Jasotzailearen kontua:</label> 
						</td>
						<td>
							<label><%=transakzioa.hartzaile_kontua%></label>
						</td>
					</tr>
					<tr>
						<td>
							<label class="bold">Transakzio id zenbakia:</label> 
						</td>
						<td>
							<label><%=transakzioa.id%></label>
						</td>
					</tr>
					<tr>
						<td>
							<label class="bold">Kopurua:</label> 
						</td>
						<td>
							<label><%=transakzioa.kopurua%>€</label>
						</td>
					</tr>
					<tr>
						<td>
							<label class="bold">Azalpena:</label> 
						</td>
						<td>
							<label><%=transakzioa.azalpena%></label>
						</td>
					</tr>
					<tr>
						<td>
							<label class="bold">Transakzio data:</label> 
						</td>
						<td>
							<label><%=transakzioa.data%></label>
						</td>
					</tr>
				</tbody>
			<%end%>
		</table>
	</div>
</section>

app/views/user_session/index.html.erb
<header class="headerMenu masthead text-center text-white" style="padding: 1rem; position:fixed; left: 0px; top:4rem; width: 100%; height: 6rem;">
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div> 
    <div class="bg-circle-4 bg-circle"></div>
    <h1 class="h3 mb-3 font-weight-bold" style="position:relative;z-index: 10;margin-top: 1.5rem; color: black">
        Please log in
    </h1>
</header>

<section><label> </label></section>

<section style="margin-top: 15%">

    <%= form_for(   :user,
    				:method => "post",
                    :url => {:controller => 'user_session', :action => 'create'},
                    :html => {:class=>"form-signin"}) do |f|%>
		
        <div class="text-center">            
            <%= f.label :nanLabel, :class=>"sr-only" %>
            <%= f.text_field :nan, :id=> "inputNan", :class=>"form-control", placeholder:"Erabiltzailea", :required => true%>
            <%= f.label :passwordLabel, :class=>"sr-only"%>
            <%= f.password_field :password, :id=> "inputPassword", :class=>"form-control", placeholder: "Pasahitza", :required => true%>
            <div class="checkbox mb-3">
                <label>
               		<input type="checkbox" value="remember-me"> Remember me
            	</label>
            </div>
            <div class="actions">
                <%= f.submit :"Log In", :class=>"btn btn-lg btn-primary btn-block submitButton"%>
            </div>
            <p class="mt-5 mb-3 text-muted"></p>
        </div>
        <center>
        	<label class="notice"><%= notice %></label>
        	<label class="alert" style="color: red"><%= alert %></label>
        </center>
    <% end %>

</section>

app/views/welcome/index.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">SareBank</h1>
      <h2 class="masthead-subheading mb-0"> Jendearen online bankua </h2>
      <a href="#gehiago" class="btn btn-primary btn-xl rounded-pill mt-5">Irakurri gehiago</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<section style="margin-bottom: 2rem;">
  <a name="gehiago"> </a>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag("1.jpg", :alt=>"1", :class=>"img-fluid rounded-circle")%>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Komisiorik gabe!</h2>
          <p>Egin nahi beste transakzio estatu barruko beste edozein kontura komisio gabe. Estatu barruko transakzioak 2 lanegunetan burutuko dira. Egin transakzioak atzerrira bakarrik 2.5€-ren truke.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <%= image_tag("2.jpg", :alt=>"2", :class=>"img-fluid rounded-circle")%>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">We salute you!</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag("3.jpg", :alt=>"3", :class=>"img-fluid rounded-circle")%>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Kontu berria</h2>
          <p>Sortu kontu berria gure bankuan guztiz dohainik eta ez zaitez kezkatu egin beharreko paperetaz, hori gure kontu. Bete online formularioa eta hasi zaitez zure kontua gaur bertan erabiltzen!</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/signin.html.erb
<header class="headerMenu masthead text-center text-white" style="padding: 1rem; position:fixed; left: 0px; top:4rem; width: 100%; height: 6rem;">
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div> 
    <div class="bg-circle-4 bg-circle"></div>
    <h1 class="h3 mb-3 font-weight-bold" style="position:relative;z-index: 10;margin-top: 1.5rem; color: black">
        Please sign up
    </h1>
</header>

<section><label> </label></section>

<section style="margin-top: 15%">

    <%= form_for(   :user,
                    :url => {:controller => 'user_sessions', :action => 'create'},
                    :html => {:class=>"form-signin"}) do |f|%>

        <div class="text-center">            
            <div class="field">
                <%= f.label :username, :class=>"sr-only" %><br />
                <%= f.text_field :username, :id=> "inputEmail", :class=>"form-control", placeholder:"Erabiltzailea", :required => true%>
            </div>
            <div class="field">
                <%= f.label :password, :class=>"sr-only"%><br />
                <%= f.password_field :password, :id=> "inputPassword", :class=>"form-control", placeholder: "Pasahitza", :required => true%>
            </div>
            <div class="checkbox mb-3">
                <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            </div>
            <div class="actions">
                <%= f.submit :"Sign Up", :class=>"btn btn-lg btn-primary btn-block submitButton"%>
            </div>
            <p class="mt-5 mb-3 text-muted"></p>
        </div>
    <% end %>

</section>